"""add fecha_publicacion to libros

Revision ID: 6cc64be1d570
Revises: 
Create Date: 2026-05-03 19:48:26.342260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc64be1d570'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_publicacion', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_libros_fecha_publicacion'), ['fecha_publicacion'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_libros_fecha_publicacion'))
        batch_op.drop_column('fecha_publicacion')

    # ### end Alembic commands ###
